### ChatGPT

POST http://localhost:8080/api/generateBasic
Content-Type: application/json

{ "message": "Why is the sky blue?"}

### ChatGPT with FAQ

POST http://localhost:8080/api/generateFaq
Content-Type: application/json

{ "message": "Where was Brown Strauss founded?"}

### ChatGPT with docs

POST http://localhost:8080/api/generateDocs
Content-Type: application/json

{ "message": "Tell me about controlled rocking steel braced frames, please."}

### ChatGPT with data

POST http://localhost:8080/api/generateData
Content-Type: application/json

{ "message": "Which wide flange beams weigh less than 40?"}

### Chroma API

GET http://localhost:8000/api/v1/collections/documents
